In [ ]:
import os
mainpath=os.path.abspath(os.getcwd())+'\\route4'
print(mainpath)
os.chdir(mainpath)

c:\Users\Dar'FusozaiVarVar\Desktop\fuznum\barnalce\fantastic-barnacle\DataAnalysis\lab2\route4

### data

In [3]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import math
#from IPython.core.display import display, HTML
#display(HTML("<style>.container { width:100% !important; }</style>"))
#display(HTML("<style>.output { height:auto !important; }</style>"))
import pandas as pd
import numpy as np
import datetime as dt
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
import sys
import configparser
import os
from scipy.fft import rfft,rfftfreq, irfft
freq=.1
interval=500
n_points=1
x=[t/n_points for t in range(int(interval*n_points))]
y=[2*np.sin(2*np.pi*freq*t) +0.3*np.sin(2*np.pi*.1*freq*t) for t in x]
yf = rfft(y)
#yf = rfft(data_t['Продольный наклон'].tolist())
abs_yf=[np.abs(yf)/len(yf) for y in yf]
xf = rfftfreq(len(y), 1 / n_points)
y=irfft(yf)
print('len=',len(y),len(yf),len(y),interval*n_points)

mainpath=os.path.abspath(os.getcwd())
print(mainpath)
os.chdir(mainpath)

data_t=pd.read_csv(mainpath+'\\route4\\3_w.csv', sep=';',encoding='cp1251')
display(data_t.head(3))
print('len(data_t=',len(data_t))


# data_t['Продольный наклон']=data_t['Продольный наклон'].interpolate(direction='both')
# data_t['Ускорение по оси X']=data_t['Ускорение по оси X'].interpolate(direction='both')
# data_t['Ускорение по оси Y']=data_t['Ускорение по оси Y'].interpolate(direction='both')
# data_t['Ускорение по оси Z']=data_t['Ускорение по оси Z'].interpolate(direction='both')
# data_t["Прод_нак"] =data_t.apply(lambda x: np.arctan(-x["Ускорение по оси Z"]/np.sqrt(x["Ускорение по оси X"]**2+x["Ускорение по оси Y"]**2))*180/np.pi,axis=1)-0.9
# display[data_t]

len= 500 251 500 500
c:\Users\Amega\barnacle\fantastic-barnacle\DataAnalysis\lab2

,Unnamed: 0,len,Скорость,Широта,Долгота,Вес мгновенный,Продольный наклон,Поперечный наклон,Высота,"Уровень топлива, литры","Уровень топлива, проценты",путь,ДВС.Расход топлива,Ускорение по оси X,Ускорение по оси Y,Ускорение по оси Z,Статус самосвала,Самосвал,Модель самосвала,Грузоподъемность,Обороты двигателя,Расчетный выходной крутящий момент двигателя (в процентах от эталонного),Текущая нагрузка двигателя,Давление в левой передней шине,Температура в левой передней шине,Давление в правой передней шине,Температура в правой передней шине,Давление в левой задней внешней шине,Температура в левой задней внешней шине,Давление в левой задней внутренней шине,Температура в левой задней внутренней шине,Давление в правой задней внутренней шине,Температура в правой задней внутренней шине,Давление в правой задней внешней шине,Температура в правой задней внешней шине,Расход топлива,Давление левый передний цилиндр,Давление правый передний цилиндр,Давление левый задний цилиндр,Давление правый задний цилиндр,уклон,azimut,isin_border,Давление левый передний цилиндр_,Давление правый передний цилиндр_,Давление левый задний цилиндр_,Давление правый задний цилиндр_,point,nom_point,"уровень давления впереди,МПа","уровень давления сзади,МПа",рекомендованная скорость_turns,Поворот влево,Поворот вправо,centr,radius,подъем,спуск,рекомендованная скорость_min,рекомендованная скорость_max
0,0,0.0,6.0,53.727758,86.854133,204.0,-2.709456,1.346258,-1.180442,NaN,90.0,0.000000,49.025,0.102988,-1.007444,0.047925,Груженный движется вперед,95,7530G,240,1303.0,17.0,26.май,812.0,30.0,796.0,30.0,876.0,49.0,880.0,46.0,1020.0,195.0,856.0,48.0,0.040854,07.май,07.июн,07.май,13.авг,-0.018701,-0.719515,0,6.0,6.0,10.фев,14.79,point_30%,1,6.0,10.фев,0.0,0,0,-,0.0,0,0,0.0,0.0
1,1,7.0,7.0,53.727715,86.854217,208.0,0.549463,0.495991,-0.161916,NaN,89.8,7.381780,100.4875,-0.013766,-1.009993,-0.009687,Груженный движется вперед,95,7530G,240,1159.0,36.0,63.24999999999999,812.0,30.0,796.0,30.0,876.0,49.0,880.0,46.0,1020.0,195.0,856.0,48.0,0.180420,06.мар,08.июн,12.апр,09.авг,0.330283,-0.879051,0,6.0,08.июл,10.фев,10.фев,point_30%,1,6.0,10.фев,0.0,0,0,-,0.0,0,0,0.0,0.0
2,2,17.0,5.0,53.727651,86.854307,205.0,1.401883,-0.277414,0.658917,NaN,89.2,9.251071,151.95,-0.037728,-0.999286,-0.024472,Груженный движется вперед,95,7530G,240,1115.5,55.0,100.0,812.0,30.0,796.0,30.0,876.0,49.0,880.0,46.0,1020.0,195.0,856.0,48.0,0.349253,04.янв,06.апр,13.0,08.мар,0.581313,-0.952206,0,6.0,6.0,10.фев,10.фев,-,0,6.0,10.фев,0.0,0,0,-,0.0,0,0,0.0,0.0

len(data_t= 196

### Проблема профиля дороги

In [6]:
import folium
from folium import plugins
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd
import numpy as np

data_1=pd.read_csv(mainpath+'\\route4\\1_w.csv',sep=';',encoding='cp1251')
data_1['xy']=data_1.apply(lambda x:[x['Широта'],x['Долгота']],axis=1)

data_2=pd.read_csv(mainpath+'\\route4\\5_w.csv',sep=';',encoding='cp1251')
data_2['xy']=data_2.apply(lambda x:[x['Широта'],x['Долгота']],axis=1)

data_1["Продольный наклон"] = np.arctan(-data_1["Ускорение по оси Z"]/np.sqrt(data_1["Ускорение по оси X"]**2+data_1["Ускорение по оси Y"]**2))*180/np.pi
data_2["Продольный наклон"] = np.arctan(-data_2["Ускорение по оси Z"]/np.sqrt(data_2["Ускорение по оси X"]**2+data_2["Ускорение по оси Y"]**2))*180/np.pi
m = folium.Map (data_1.loc[0,'xy'], zoom_start = 13)
title_html = '''<h3 align="center" style="font-size:21px"><b>{}</b></h3>'''.format('Рейсы самосвала КС 1982')

m.get_root().html.add_child(folium.Element(title_html)) 

route = folium.PolyLine (list(data_1['xy']),вес = 3, color = 'green', непрозрачность = 0.8).add_to (m)
route = folium.PolyLine (list(data_2['xy']),вес = 3, color = 'blue', непрозрачность = 0.8).add_to (m)

display(m)
m.save('map1989.html')

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Продольный наклон'],mode='lines', name='продольный наклон_1'),secondary_y=True)
#fig.add_trace(go.Scatter(x=data_2['len'], y=data_2['Продольный наклон'],mode='lines', name='продольный наклон_2'),secondary_y=True)

fig.update_layout(title_text='Профиль дороги ',width=1100,height=500)
fig.show()

### Спектр гармонического сигнала

In [7]:
import math
import pandas as pd
import numpy as np
from scipy.fft import rfft,rfftfreq, irfft
import plotly.graph_objects as go
from plotly.subplots import make_subplots

freq=1
interval=5
n_points=200
x=[t/n_points for t in range(int(interval*n_points))] 
y=[2*np.sin(2*np.pi*freq*t) +0.3*np.sin(2*np.pi*10*freq*t) for t in x]

fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(go.Scatter(x=x, y=y,mode='lines', name='Гармоническая функция'),secondary_y=True)
fig.update_layout(title_text='Функция ',width=1100,height=500)
fig.show()

yf = rfft(y)
abs_yf=[np.abs(i)/len(yf) for i in yf]
xf = rfftfreq(len(y), 1 / n_points)

fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(go.Bar(x=xf[:100], y=abs_yf[:100],width=.1, name='spectr'),secondary_y=False)
fig.update_layout(title_text='Спектр  ',width=1200,height=500)
fig.show() 

ind=min([i for i in range(len(xf)) if xf[i]>=10])
yf[ind:]=0
abs_yf=[np.abs(i)/len(yf) for i in yf]

fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(go.Bar(x=xf[:100], y=abs_yf[:100],width=.1, name='spectr'),secondary_y=False)
fig.update_layout(title_text='Спектр  ',width=1200,height=500)
fig.show() 

y=irfft(yf)

fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(go.Scatter(x=x, y=y,mode='lines', name='Гармоническая функция'),secondary_y=True)
fig.update_layout(title_text='Функция ',width=1100,height=500)
fig.show()

### Спектральный анализ продольного наклона

In [8]:
import pandas as pd
from scipy.fft import rfft,rfftfreq, irfft
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots

data_1=pd.read_csv(mainpath+'\\route4\\280_w.csv',sep=';',encoding='cp1251')
data_1['xy']=data_1.apply(lambda x:[x['Широта'],x['Долгота']],axis=1)

if len(data_1)%2==0:
   pass
else:
    data_1.drop(0,inplace=True)
    data_1.reset_index(drop=True,inplace=True)

    
data_1["Продольный наклон"] = np.arctan(-data_1["Ускорение по оси Z"]/np.sqrt(data_1["Ускорение по оси X"]**2+data_1["Ускорение по оси Y"]**2))*180/np.pi

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Продольный наклон'],mode='lines', name='продольный наклон_1'),secondary_y=True)

fig.update_layout(title_text='Профиль дороги ',width=1100,height=500)
fig.show()

n_points=10

yf = rfft(data_1['Продольный наклон'])
abs_yf=[np.abs(i)/len(yf) for i in yf] 
xf = rfftfreq(len(data_1), 1 / n_points)

fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(go.Bar(x=xf[:100], y=abs_yf[:100],width=.01, name='spectr'),secondary_y=False)

fig.update_layout(title_text='Спектр_1 ',width=1200,height=500)
fig.show()

ind_= min([i for i in range(len(xf)) if xf[i]>=0.5])

yf[ind_:]=0
abs_yf=[np.abs(y)/len(yf) for y in yf] 
data_1["Прод_нак_fft"]=irfft(yf)
prod_nak_fft_1=data_1["Прод_нак_fft"].tolist()

                                                                                                                                                                                                                                                                                                                                                                                                       
fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Продольный наклон'],mode='lines', name='продольный наклон_1'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Прод_нак_fft'],mode='lines', name='продольный наклон_1_fft'),secondary_y=True)

fig.update_layout(title_text='Профиль дороги отфильтрованный',width=1100,height=500)
fig.show()
fig.write_html("Профиль дороги.html")
data_1["Высота_fft"] = data_1.loc[0,"Высота"]
data_1=data_1.copy()
for i in range(1, len(data_1)):
    data_1.loc[i, "Высота_fft"] = data_1.loc[i-1, "Высота_fft"] + (data_1["len"].iloc[i] - data_1["len"].iloc[i-1]) * np.tan((data_1["Прод_нак_fft"].iloc[i-1]-0.8)*np.pi/180.)   

fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Высота'],mode='lines', name='Высота_1'),secondary_y=False)
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Высота_fft'],mode='lines', name='Высота_1_fft'),secondary_y=False)

fig.update_layout(title_text='Проверка профиля дороги высотой',width=1100,height=500)
fig.show()
fig.write_html("Проверка высотой.html")

## Спектральный анализ поперечного наклона

In [9]:
import pandas as pd
from scipy.fft import rfft,rfftfreq, irfft
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots


data_1=pd.read_csv(mainpath+'\\route4\\1_w.csv',sep=';',encoding='cp1251')
data_1['xy']=data_1.apply(lambda x:[x['Широта'],x['Долгота']],axis=1)

if len(data_1)%2==0:
   pass
else:
    data_1.drop(0,inplace=True)
    data_1.reset_index(drop=True,inplace=True)

data_1["Поперечный наклон"] = np.arctan(-data_1["Ускорение по оси X"]/np.sqrt(data_1["Ускорение по оси Z"]**2+data_1["Ускорение по оси Y"]**2))*180/np.pi
data_2["Поперечный наклон"] = np.arctan(-data_2["Ускорение по оси X"]/np.sqrt(data_2["Ускорение по оси Z"]**2+data_2["Ускорение по оси Y"]**2))*180/np.pi

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Поперечный наклон'],mode='lines', name='Поперечный наклон_1'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_2['len'], y=data_2['Поперечный наклон'],mode='lines', name='Поперечный наклон_2'),secondary_y=True)

fig.update_layout(title_text='Поперечный профиль дороги ',width=1100,height=500)
fig.show()

n_points=10

yf = rfft(data_1['Поперечный наклон'])
abs_yf=[np.abs(i)/len(yf) for i in yf] 
xf = rfftfreq(len(data_1), 1 / n_points)

fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(go.Bar(x=xf[:100], y=abs_yf[:100],width=.01, name='spectr'),secondary_y=False)

fig.update_layout(title_text='Спектр_1 ',width=1200,height=500)
fig.show()

ind_=min([i for i in range(len(xf)) if xf[i]>=0.5])

yf[ind_:]=0
abs_yf=[np.abs(y)/len(yf) for y in yf] 
data_1["Поп_нак_fft"]=irfft(yf)
pop_nak_fft_1=data_1["Поп_нак_fft"].tolist()

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Поперечный наклон'],mode='lines', name='Поперечный наклон_1'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Поп_нак_fft'],mode='lines', name='Поперечный наклон_1_fft'),secondary_y=True)

fig.update_layout(title_text='Поперечный профиль дороги отфильтрованный',width=1100,height=500)
fig.show()
fig.write_html("Профиль поперечного наклона.html")

### Датчики давления

In [11]:
import pandas as pd
from scipy.fft import rfft,rfftfreq, irfft
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots


data_1=pd.read_csv(mainpath+'\\route4\\1_w.csv',sep=';',encoding='cp1251')
data_1['xy']=data_1.apply(lambda x:[x['Широта'],x['Долгота']],axis=1)

if len(data_1)%2==0:
   pass
else:
    data_1.drop(0,inplace=True)
    data_1.reset_index(drop=True,inplace=True)


data_2=pd.read_csv(mainpath+'\\route4\\5_w.csv',sep=';',encoding='cp1251')
data_2['xy']=data_2.apply(lambda x:[x['Широта'],x['Долгота']],axis=1)

if len(data_2)%2==0:
    pass
else:
    data_2.drop(0,inplace=True)
    data_2.reset_index(drop=True,inplace=True)

n_points=10
tags=['Давление левый передний цилиндр','Давление правый передний цилиндр','Давление левый задний цилиндр','Давление правый задний цилиндр']
for tag in tags:
    yf = rfft(data_1[tag])
    abs_yf=[np.abs(i)/len(yf) for i in yf] 
    xf = rfftfreq(len(data_1), 1 / n_points)
    
    fig = make_subplots(specs=[[{"secondary_y": True}]])
    fig.add_trace(go.Bar(x=xf[1:100], y=abs_yf[1:100],width=.01, name='Спектр_1 '+tag),secondary_y=False)
    
    fig.update_layout(title_text='Спектр '+tag,width=1200,height=500)
    fig.show()
    
    ind_=min([i for i in range(len(xf)) if xf[i]>=0.5])
    
    yf[:ind_]=0
    abs_yf=[np.abs(y)/len(yf) for y in yf] 
    data_1[tag+"_fft"]=irfft(yf)


fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление левый передний цилиндр'],mode='lines', name='левый передний_1'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление левый передний цилиндр_fft'],mode='lines', name='левый передний_1_fft'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление правый передний цилиндр'],mode='lines', name='правый передний цилиндр_1'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление правый передний цилиндр_fft'],mode='lines', name='правый передний_1_fft'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление левый передний цилиндр_fft'],mode='lines', name='левый передний_1_fft'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление правый передний цилиндр_fft'],mode='lines', name='правый передний_1_fft'),secondary_y=True)

fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление левый задний цилиндр'],mode='lines', name='левый задний_1'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление левый задний цилиндр_fft'],mode='lines', name='левый задний_1_fft'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление правый задний цилиндр'],mode='lines', name='правый задний цилиндр_1'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление правый задний цилиндр_fft'],mode='lines', name='правый задний_1_fft'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_1['len'], y=prod_nak_fft_1,mode='lines', name='продольный наклон_1_fft'),secondary_y=False)
fig.add_trace(go.Scatter(x=data_1['len'], y=pop_nak_fft_1,mode='lines', name='поперечный наклон_1_fft'),secondary_y=False)
# fig.add_trace(go.Scatter(x=data_1['len'], y=prod_nak_fft_2,mode='lines', name='продольный наклон_2_fft'),secondary_y=False)
# fig.add_trace(go.Scatter(x=data_1['len'], y=pop_nak_fft_2,mode='lines', name='поперечный наклон_2_fft'),secondary_y=False)


fig.update_layout(title_text=tag+' отфильтрованное',width=1100,height=500)
fig.show()
fig.write_html("датчики давления.html")

### Анализ ям

In [17]:
import pandas as pd
from scipy.fft import rfft,rfftfreq, irfft
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import sys
import configparser



critical_length_for_holes=10

data_1=pd.read_csv(mainpath+'\\route4\\1_w.csv',sep=';',encoding='cp1251')
data_1['xy']=data_1.apply(lambda x:[x['Широта'],x['Долгота']],axis=1)
dump_code=data_1.loc[0,'Самосвал']
dump_width=float(300)/1000.
print('dump_code=',dump_code,' dump_width=',dump_width)

if len(data_1)%2==0:
   pass
else:
    data_1.drop(0,inplace=True)
    data_1.reset_index(drop=True,inplace=True)


data_2=pd.read_csv(mainpath+'\\route4\\5_w.csv',sep=';',encoding='cp1251')
data_2['xy']=data_2.apply(lambda x:[x['Широта'],x['Долгота']],axis=1)

if len(data_2)%2==0:
    pass
else:
    data_2.drop(0,inplace=True)
    data_2.reset_index(drop=True,inplace=True)

n_points=10
tags=['Давление левый передний цилиндр','Давление правый передний цилиндр','Давление левый задний цилиндр','Давление правый задний цилиндр']
for tag in tags:
    yf = rfft(data_1[tag])
    abs_yf=[np.abs(i)/len(yf) for i in yf]
    xf = rfftfreq(len(data_1), 1 / n_points)

    fig = make_subplots(specs=[[{"secondary_y": True}]])
    fig.add_trace(go.Bar(x=xf[1:100], y=abs_yf[1:100],width=.01, name='Спектр_1 '+tag),secondary_y=False)

    fig.update_layout(title_text='Спектр '+tag,width=1200,height=500)
    fig.show()

    ind_=max([i for i in range(len(xf)) if xf[i]<=0.5])

    yf[:ind_]=0
    abs_yf=[np.abs(y)/len(yf) for y in yf]
    data_1[tag+"_hole"]=irfft(yf)

#yf = rfft(data_2['Ускорение по оси Z'])
#abs_yf=[np.abs(i)/len(yf) for i in yf]
#xf = rfftfreq(len(data_2), 1 / n_points)
#ind_=max([i for i in range(len(xf)) if xf[i]<=0.5])
#yf[:ind_]=0
#abs_yf=[np.abs(y)/len(yf) for y in yf]
#data_2["ямы_fft"]=irfft(yf)
print(data_1.columns)
#display(data_1[['len','point','nom_point']].head(3))
lf_l=data_1[data_1['Давление левый передний цилиндр_hole']>0]['Давление левый передний цилиндр_hole'].quantile(0.5)
lf_r=data_1[data_1['Давление правый передний цилиндр_hole']>0]['Давление правый передний цилиндр_hole'].quantile(0.5)
rf_l=data_1[data_1['Давление левый задний цилиндр_hole']>0]['Давление левый задний цилиндр_hole'].quantile(0.5)
rf_r=data_1[data_1['Давление правый задний цилиндр_hole']>0]['Давление правый задний цилиндр_hole'].quantile(0.5)
print('lf_правый=',lf_l,' lf_левый=',lf_r,' rf_левый=',rf_l,' rf_правый=',rf_r)
lf=(lf_l+lf_r)/2
lr=(rf_l+rf_r)/2
# data_1=funrou.pit_marking((lf_l+lf_r)/2,(rf_l+rf_r)/2,data_1,critical_length_for_holes,amper_param,dump_width)
print(data_1.columns)
#data_1=funrou.point_align(data_1,critical_length_for_holes)
print(data_1.columns)
fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление левый передний цилиндр'],mode='lines', name='левый передний_1'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление левый передний цилиндр_hole'],mode='lines', name='левый передний_1_hole'),secondary_y=False)
# display(data_1.head(1))
# fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление левый передний цилиндр_hole_'],mode='lines', name='левый передний_hole_'),secondary_y=False)

fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление правый передний цилиндр'],mode='lines', name='правый передний цилиндр_1'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление правый передний цилиндр_hole'],mode='lines', name='правый передний_1_hole'),secondary_y=False)
# fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление правый передний цилиндр_hole_'],mode='lines', name='правый передний_1_hole_'),secondary_y=False)

fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление левый задний цилиндр'],mode='lines', name='левый задний_1'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление левый задний цилиндр_hole'],mode='lines', name='левый задний_1_hole'),secondary_y=False)
# fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление левый задний цилиндр_hole_'],mode='lines', name='левый задний_1_hole_'),secondary_y=False)

fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление правый задний цилиндр'],mode='lines', name='правый задний цилиндр_1'),secondary_y=True)
fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление правый задний цилиндр_hole'],mode='lines', name='правый задний_1_hole'),secondary_y=False)
# fig.add_trace(go.Scatter(x=data_1['len'], y=data_1['Давление правый задний цилиндр_hole_'],mode='lines', name='правый задний_1_hole_'),secondary_y=False)
fig.add_trace(go.Scatter(x=data_1['len'], y=prod_nak_fft_1,mode='lines', name='продольный наклон_1_fft'),secondary_y=False)
#fig.add_trace(go.Scatter(x=data_1['len'], y=pop_nak_fft_1,mode='lines', name='поперечный наклон_1_fft'),secondary_y=False)
#fig.add_trace(go.Scatter(x=data_1['len'], y=prod_nak_fft_2,mode='lines', name='продольный наклон_2_fft'),secondary_y=False)
#fig.add_trace(go.Scatter(x=data_1['len'], y=pop_nak_fft_2,mode='lines', name='поперечный наклон_2_fft'),secondary_y=False)


fig.update_layout(title_text=tag+' ямы отфильтрованные',width=1100,height=500)
fig.show()
fig.write_html("ямы.html")

display(data_1.head(3))

dump_code= 95  dump_width= 0.3

Index(['Unnamed: 0', 'len', 'Скорость', 'Широта', 'Долгота', 'Вес мгновенный', 'Продольный наклон', 'Поперечный наклон', 'Высота', 'Уровень топлива, литры', 'Уровень топлива, проценты', 'путь', 'ДВС.Расход топлива', 'Ускорение по оси X', 'Ускорение по оси Y', 'Ускорение по оси Z', 'Статус самосвала', 'Самосвал', 'Модель самосвала', 'Грузоподъемность', 'Обороты двигателя', 'Расчетный выходной крутящий момент двигателя (в процентах от эталонного)', 'Текущая нагрузка двигателя', 'Давление в левой передней шине', 'Температура в левой передней шине', 'Давление в правой передней шине', 'Температура в правой передней шине', 'Давление в левой задней внешней шине', 'Температура в левой задней внешней шине', 'Давление в левой задней внутренней шине', 'Температура в левой задней внутренней шине', 'Давление в правой задней внутренней шине', 'Температура в правой задней внутренней шине', 'Давление в правой задней внешней шине', 'Температура в правой задней внешней шине', 'Расход топлива',
       'Давление левый передний цилиндр', 'Давление правый передний цилиндр', 'Давление левый задний цилиндр', 'Давление правый задний цилиндр', 'уклон', 'azimut', 'isin_border', 'Давление левый передний цилиндр_', 'Давление правый передний цилиндр_', 'Давление левый задний цилиндр_', 'Давление правый задний цилиндр_', 'point', 'nom_point', 'уровень давления впереди,МПа', 'уровень давления сзади,МПа', 'рекомендованная скорость_turns', 'Поворот влево', 'Поворот вправо', 'centr', 'radius', 'подъем', 'спуск', 'рекомендованная скорость_min', 'рекомендованная скорость_max', 'xy', 'Давление левый передний цилиндр_hole', 'Давление правый передний цилиндр_hole', 'Давление левый задний цилиндр_hole', 'Давление правый задний цилиндр_hole'],
      dtype='str')
lf_правый= 0.460516412909827  lf_левый= 0.5032393868886267  rf_левый= 0.4933098696280457  rf_правый= 0.5956393353775947
Index(['Unnamed: 0', 'len', 'Скорость', 'Широта', 'Долгота', 'Вес мгновенный', 'Продольный наклон', 'Поперечный наклон', 'Высота', 'Уровень топлива, литры', 'Уровень топлива, проценты', 'путь', 'ДВС.Расход топлива', 'Ускорение по оси X', 'Ускорение по оси Y', 'Ускорение по оси Z', 'Статус самосвала', 'Самосвал', 'Модель самосвала', 'Грузоподъемность', 'Обороты двигателя', 'Расчетный выходной крутящий момент двигателя (в процентах от эталонного)', 'Текущая нагрузка двигателя', 'Давление в левой передней шине', 'Температура в левой передней шине', 'Давление в правой передней шине', 'Температура в правой передней шине', 'Давление в левой задней внешней шине', 'Температура в левой задней внешней шине', 'Давление в левой задней внутренней шине', 'Температура в левой задней внутренней шине', 'Давление в правой задней внутренней шине', 'Температура в правой задней внутренней шине', 'Давление в правой задней внешней шине', 'Температура в правой задней внешней шине', 'Расход топлива',
       'Давление левый передний цилиндр', 'Давление правый передний цилиндр', 'Давление левый задний цилиндр', 'Давление правый задний цилиндр', 'уклон', 'azimut', 'isin_border', 'Давление левый передний цилиндр_', 'Давление правый передний цилиндр_', 'Давление левый задний цилиндр_', 'Давление правый задний цилиндр_', 'point', 'nom_point', 'уровень давления впереди,МПа', 'уровень давления сзади,МПа', 'рекомендованная скорость_turns', 'Поворот влево', 'Поворот вправо', 'centr', 'radius', 'подъем', 'спуск', 'рекомендованная скорость_min', 'рекомендованная скорость_max', 'xy', 'Давление левый передний цилиндр_hole', 'Давление правый передний цилиндр_hole', 'Давление левый задний цилиндр_hole', 'Давление правый задний цилиндр_hole'],
      dtype='str')
Index(['Unnamed: 0', 'len', 'Скорость', 'Широта', 'Долгота', 'Вес мгновенный', 'Продольный наклон', 'Поперечный наклон', 'Высота', 'Уровень топлива, литры', 'Уровень топлива, проценты', 'путь', 'ДВС.Расход топлива', 'Ускорение по оси X', 'Ускорение по оси Y', 'Ускорение по оси Z', 'Статус самосвала', 'Самосвал', 'Модель самосвала', 'Грузоподъемность', 'Обороты двигателя', 'Расчетный выходной крутящий момент двигателя (в процентах от эталонного)', 'Текущая нагрузка двигателя', 'Давление в левой передней шине', 'Температура в левой передней шине', 'Давление в правой передней шине', 'Температура в правой передней шине', 'Давление в левой задней внешней шине', 'Температура в левой задней внешней шине', 'Давление в левой задней внутренней шине', 'Температура в левой задней внутренней шине', 'Давление в правой задней внутренней шине', 'Температура в правой задней внутренней шине', 'Давление в правой задней внешней шине', 'Температура в правой задней внешней шине', 'Расход топлива',
       'Давление левый передний цилиндр', 'Давление правый передний цилиндр', 'Давление левый задний цилиндр', 'Давление правый задний цилиндр', 'уклон', 'azimut', 'isin_border', 'Давление левый передний цилиндр_', 'Давление правый передний цилиндр_', 'Давление левый задний цилиндр_', 'Давление правый задний цилиндр_', 'point', 'nom_point', 'уровень давления впереди,МПа', 'уровень давления сзади,МПа', 'рекомендованная скорость_turns', 'Поворот влево', 'Поворот вправо', 'centr', 'radius', 'подъем', 'спуск', 'рекомендованная скорость_min', 'рекомендованная скорость_max', 'xy', 'Давление левый передний цилиндр_hole', 'Давление правый передний цилиндр_hole', 'Давление левый задний цилиндр_hole', 'Давление правый задний цилиндр_hole'],
      dtype='str')

,Unnamed: 0,len,Скорость,Широта,Долгота,Вес мгновенный,Продольный наклон,Поперечный наклон,Высота,"Уровень топлива, литры","Уровень топлива, проценты",путь,ДВС.Расход топлива,Ускорение по оси X,Ускорение по оси Y,Ускорение по оси Z,Статус самосвала,Самосвал,Модель самосвала,Грузоподъемность,Обороты двигателя,Расчетный выходной крутящий момент двигателя (в процентах от эталонного),Текущая нагрузка двигателя,Давление в левой передней шине,Температура в левой передней шине,Давление в правой передней шине,Температура в правой передней шине,Давление в левой задней внешней шине,Температура в левой задней внешней шине,Давление в левой задней внутренней шине,Температура в левой задней внутренней шине,Давление в правой задней внутренней шине,Температура в правой задней внутренней шине,Давление в правой задней внешней шине,Температура в правой задней внешней шине,Расход топлива,Давление левый передний цилиндр,Давление правый передний цилиндр,Давление левый задний цилиндр,Давление правый задний цилиндр,уклон,azimut,isin_border,Давление левый передний цилиндр_,Давление правый передний цилиндр_,Давление левый задний цилиндр_,Давление правый задний цилиндр_,point,nom_point,"уровень давления впереди,МПа","уровень давления сзади,МПа",рекомендованная скорость_turns,Поворот влево,Поворот вправо,centr,radius,подъем,спуск,рекомендованная скорость_min,рекомендованная скорость_max,xy,Давление левый передний цилиндр_hole,Давление правый передний цилиндр_hole,Давление левый задний цилиндр_hole,Давление правый задний цилиндр_hole
0,0,0.0,7.0,53.727590,86.854016,202.0,4.158987,3.245764,1.299945,2446.0,88.8,0.000000,119.925,0.027531,-0.939125,-0.068319,Груженный движется вперед,95,7530G,240,945.0,49.0,100.0,800.0,29.0,808.0,26.0,888.0,46.0,888.0,41.0,8.0,40.0,856.0,45.0,0.133250,6.6,11.0,7.8,14.3,4.626917,-1.305806,0,7.2,10.44,10.1,14.645,point_30%,1,7.2,10.1,0.0,0,0,-,0.0,0,0,0.0,0.0,"[53.7275905, 86.8540161]",-0.251940,1.736952,-2.376160,1.828030
1,1,8.0,7.0,53.727520,86.854048,207.0,5.604727,1.894424,1.406299,2446.0,87.6,8.097400,267.225,0.011216,-0.987050,-0.096870,Груженный движется вперед,95,7530G,240,1404.0,77.0,100.0,800.0,29.0,808.0,26.0,888.0,46.0,888.0,41.0,8.0,40.0,856.0,45.0,0.430167,3.8,8.0,10.3,10.8,3.157684,-1.369111,0,7.2,10.44,10.1,14.645,point_30%,1,7.2,10.1,0.0,0,0,-,0.0,0,0,0.0,0.0,"[53.7275203, 86.8540483]",-3.114734,-1.368343,0.155978,-1.291852
2,2,17.0,9.0,53.727444,86.854075,205.0,0.415264,0.729007,1.384253,2446.0,86.8,8.646824,153.400,0.060161,-0.982971,-0.007138,Груженный движется вперед,95,7530G,240,1053.0,58.0,100.0,800.0,29.0,808.0,26.0,888.0,46.0,888.0,41.0,8.0,40.0,856.0,45.0,0.600611,5.6,8.9,8.0,13.4,1.914892,-1.224417,0,7.2,10.44,10.1,14.645,point_30%,1,7.2,10.1,0.0,0,0,-,0.0,0,0,0.0,0.0,"[53.7274442, 86.8540746]",-1.403386,-0.553524,-2.166502,1.654965

# Визуализация ям

In [19]:
import folium 

m = folium.Map (data_1.loc[0,'xy'], zoom_start = 13)
title_html = '''<h3 align="center" style="font-size:21px"><b>{}</b></h3>'''.format('Рейсы самосвала КС 1982 ямы')

m.get_root().html.add_child(folium.Element(title_html)) 

route = folium.PolyLine (list(data_1['xy']),вес = 3, color = 'green', непрозрачность = 0.8).add_to (m)
route = folium.PolyLine (list(data_2['xy']),вес = 3, color = 'blue', непрозрачность = 0.8).add_to (m)
tags = ['Давление левый передний цилиндр_hole', 'Давление правый передний цилиндр_hole', 'Давление левый задний цилиндр_hole', 'Давление правый задний цилиндр_hole']
for l in data_1:
    for t in tags:
        if l.loc[t] < 0:
            folium.CircleMarker(
                location=[-27.55, -48.8],
                radius=dump_width,
                color="cornflowerblue",
                stroke=False,
                fill=True,
                fill_opacity=0.6,
                opacity=1,
                popup="{} pixels".format(radius),
                tooltip="I am in pixels",
            ).add_to(m)

display(m)
m.save('map1989holes.html')

AttributeError: 'str' object has no attribute 'loc'

In [5]:
#data_1=funrou.point_align(data_1,critical_length_for_holes)
lf=(lf_l+lf_r)/2
rf=(rf_l+rf_r)/2
print('уровни впереди:',lf,lf*1.5,lf*2.5,lf*3.5,lf*4.5,lf*5.5)
print('уровни сзади:',rf,rf*1.5,rf*2.5,rf*3.5,rf*4.5,rf*5.5)
display(data_1[['len','Давление левый передний цилиндр_hole_','Давление правый передний цилиндр_hole_','Давление левый задний цилиндр_hole_',
        'Давление правый задний цилиндр_hole_','point','point_dist']])
#display(data_1.head(3))
#, 'Давление левый передний цилиндр_30%','Давление левый передний цилиндр_60%',
#                'Давление левый передний цилиндр_90%']].head(1))
print(data_1['Давление левый передний цилиндр_hole'].median())
print(data_1['Давление правый передний цилиндр_hole'].mean())
print(data_1['Давление левый задний цилиндр_hole'].mean())
print(data_1['Давление правый задний цилиндр_hole'].mean())
print('quantile=',data_1[data_1['Давление левый задний цилиндр_hole']>0]['Давление левый задний цилиндр_hole'].quantile(0.5))

NameError: name 'lf_l' is not defined