In [1]:
import pandas as pd 
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 10000)
pd.set_option('display.width', 1000)


sheets = pd.ExcelFile(f'./PQM - podatki za pilotni projekt (OCR12VM) - ENG.xlsx')
print(sheets.sheet_names)

data = pd.read_excel(f'./PQM - podatki za pilotni projekt (OCR12VM) - ENG.xlsx', sheet_name='Table1 (basic)', skiprows=[0])
data.drop(['QualityRequirement', 'QualNo', 'CustID','CustVer','InternalVer','MetalRavneQualityName','SteelGroup','Month','Year'], axis=1, inplace=True)
data.drop_duplicates(subset=['HeatNo'],keep='first',inplace=True)

data.dropna(subset=['Cr_Last_EOP','Mo_Last_EOP','Ni_Last_EOP','V_Last_EOP','W_Last_EOP'],inplace=True)


data_=pd.read_excel('PQM - podatki za pilotni projekt (OCR12VM) - ENG.xlsx',sheet_name='Table2 (limits)',skiprows=[0])
data_.drop(['QualityRequirement','QualNo','CustID','CustVer','InternalVer','MetalRavneQualityName','SteelGroup','Month','Year'],axis=1,inplace=True)
data_.drop(['Date','Cr_Final','Ni_Final','Mo_Final','V_Final','W_Final'],axis=1,inplace=True)
data_.drop_duplicates(subset=['HeatNo'], keep='first', inplace=True)

data=data.merge(data_,on='HeatNo',how='inner')

data_=pd.read_excel('PQM - podatki za pilotni projekt (OCR12VM) - ENG.xlsx',sheet_name='Table4 (alloys)',skiprows=[0])
data.drop(['LFVD_FeCrA', 'LFVD_FeCrC','LFVD_NiGran', 'LFVD_NiKatode','LFVD_FeMo', 'LFVD_Polymox','LFVD_FeV','LFVD_FeW72','LFVD_WPaketi'],axis=1,inplace=True)
data_.drop_duplicates(subset=['HeatNo'], keep='first', inplace=True)

data=data.merge(data_,on='HeatNo',how='inner')

data_=pd.read_excel('PQM - podatki za pilotni projekt (OCR12VM) - ENG.xlsx',sheet_name='Table7 (head)',skiprows=[0])
data_.drop_duplicates(subset=['HeatNo'], keep='first', inplace=True)

data=data.merge(data_,on='HeatNo',how='inner')

data_=pd.read_excel('PQM - podatki za pilotni projekt (OCR12VM) - ENG.xlsx',sheet_name='Table8 (scrap)',skiprows=[0])
data_.drop_duplicates(subset=['HeatNo'], keep='first', inplace=True)

data=data.merge(data_,on='HeatNo',how='inner')

data_=pd.read_excel('PQM - podatki za pilotni projekt (OCR12VM) - ENG.xlsx',sheet_name='Table9 (all. scr.)',skiprows=[0])
data_.drop_duplicates(subset=['HeatNo'], keep='first', inplace=True)

data=data.merge(data_,on='HeatNo',how='inner')

data_=pd.read_excel('PQM - podatki za pilotni projekt (OCR12VM) - ENG.xlsx',sheet_name='Table10 (unall. scr.)',skiprows=[0])
data_.drop_duplicates(subset=['HeatNo'], keep='first', inplace=True)

data=data.merge(data_,on='HeatNo',how='inner')

display(data.head(3))
print('всего строк=',len(data))
print('всего столбцов=',len(data.columns))
data.to_csv('итоговая таблица.csv',sep=';',index=False)

['Table1 (basic)', 'Table2 (limits)', 'Table3 (events)', 'Table4 (alloys)', 'Table5 (temps)', 'Table6 (weights)', 'Table7 (head)', 'Table8 (scrap)', 'Table9 (all. scr.)', 'Table10 (unall. scr.)']

,HeatNo,Date,TotalIngotsWeight,PouringScrap,OtherScrap,Last_EOP,Cr_Last_EOP,Cr_Final,Ni_Last_EOP,Ni_Final,Mo_Last_EOP,Mo_Final,V_Last_EOP,V_Final,W_Last_EOP,W_Final,Cr_LowerLimit,Cr_Target,Cr_UpperLimit,Ni_LowerLimit,Ni_Target,Ni_UpperLimit,Mo_LowerLimit,Mo_Target,Mo_UpperLimit,V_LowerLimit,V_Target,V_UpperLimit,W_LowerLimit,W_Target,W_UpperLimit,LFVD_AlBloki,LFVD_AlGran,LFVD_Boksit,LFVD_CaO,LFVD_CaSi,LFVD_CASIfi13,LFVD_Cfi13,LFVD_CoMet,LFVD_Cu,LFVD_EPŽŽlindra,LFVD_FeAl,LFVD_FeB,LFVD_FeBŽica,LFVD_FeCrNit,LFVD_FeCrA,LFVD_FeCrC,LFVD_FeCrCSi,LFVD_FeCrC51,LFVD_FeMnA,LFVD_FeMnC,LFVD_FeMo,LFVD_FeNbTa,LFVD_FeNbTafi13,LFVD_FeS,LFVD_FeSi,LFVD_FeSiZrŽica,LFVD_FeTi,LFVD_FeTifi13,LFVD_FeV,LFVD_FeW72,LFVD_KarboritMleti,LFVD_MnMet,LFVD_NiGran,LFVD_NiKatode,LFVD_NiOksid,LFVD_OdpCu,LFVD_Polymox,LFVD_SŽica,LFVD_SiMet,LFVD_SiMn,LFVD_SLAGMAG65B,LFVD_KarboritZaVpih,LFVD_Ni90,LFVD_AlŽica,LFVD_Molyquick,LFVD_AlOplašèenaŽica,LFVD_BelaŽlindra,LFVD_Kisik,LFVD_KalcijevKarbid,LFVD_WPaketi,LFVD_SintŽlindra,LFVD_ShiftHead,Fill#1_ScrapName,Fill#1_ScrapWeight,Fill#2_ScrapName,Fill#2_ScrapWeight,Fill#3_ScrapName,Fill#3_ScrapWeight,Fill#4_ScrapName,Fill#4_ScrapWeight,Fill#5_ScrapName,Fill#5_ScrapWeight,Fill#6_ScrapName,Fill#6_ScrapWeight,PV_MKK,PV_PO102,PV_OCR12SPW,PV_OCR8W,PV_PO180,PV_PT181,PV_PT202,PV_PT212,PV_OH239,PV_OSIKRO3,PV_OW4,PV_OCR8VMS,PV_CRV3,PV_OH250,PV_OH252,PV_OH255,PV_OH257,PV_OH258,PV_OH260,PV_OH236NI,PV_UTOPMONI,PV_PKTB,PV_PK3NI,PV_PK332,PV_PK335,PV_PK338,PV_PK340,PV_PK11S,PV_PK343,PV_18MNCR4,PV_PK346,PV_INVAR36,PV_EMCR,PV_SIVA_LITINA,PV_CK10,PV_OC100EX,PV_EC80,PV_VCMO140,PV_VCMO230,PV_31CRV3,PV_ECN150,PV_ECN35,PV_VCNMO200,PV_UTOPNICU,PV_OH807,PV_OCR4PR,PV_OCR12,PV_OCR12SP,PV_OCR12EX,PV_CRV,PV_TMCN2,PV_TMCN1,PV_OSIKRO4,PV_OW1,PV_OCR12VM,PV_CRV2,PV_OSV1,PV_OW6,PV_145V33,PV_UTOP3,PV_UTOPMO2,PV_UTOPEX1,PV_UTOP1,PV_UTOP2,PV_UTOPCO,PV_UTOPEX3,PV_UTOPMO4,PV_UTOPCO2,PV_OV862,PV_UTOPMO6,PV_UTOP33,PV_UTOPSP,PV_UTOPCO3,PV_BRW,PV_BRW1,PV_BRC,PV_BRM2,PV_BRM1,PV_BRM,PV_BRCV,PV_BRC3,PV_BRU,PV_BRCMO,PV_BRCMO2,PV_UTOPTI,PV_12MN,PV_PK2,PV_RAVNIN2,PV_RAVNIN3,PV_RAVNIN4,PV_PK2SP,PV_PK11,PV_PK12,PV_PK13,PV_PKAS,PV_PK15,PV_PK19,PV_PK20,PV_PT929,PV_PK5,PV_PK5M,PV_28304N,PV_PK939,PV_X45,PV_PK942,PV_RAVNAL2,PV_PK10,PV_19MNCR18,PV_214N,PV_OCR8W_OSTRUŽKI,PV_CRV3_OSTRUŽKI,PV_PK335_OSTRUŽKI,PV_CRMO_OSTRUŽKI,PV_CRMO_DROBIŽ,PV_VCNMO200_DROBIŽ,PV_TMCN2_OSTRUŽKI,PV_OCR12VM_OSTRUŽKI,PV_POSEBNA_JEKLA_OSTRUŽKI,PV_BRM2_OSTRUŽKI,PV_E1,PV_E3,PV_E6,PV_E8,PV_Kore,PV_GRODELJ,PV_E40
0,73579,2004-07-27 00:17:10,49440.0,600.0,2000.0,2.0,9.71,11.30,0.20,0.21,0.12,0.71,0.03,0.90,0.01,0.02,11.1,11.26,11.75,0,0,0.25,0.7,0.73,0.8,0.9,0.93,1.0,0,0,0.2,26,0,200,600,0,16.5,20.6,0,0,0,0,0,0,0,0,2400,0,0,0,20,520,0,0,0,130,0,0,0,580,0,125,0,0,0,0,0,0,0.0,0,0,0,0,0,0.0,0,0.0,0,0,0,0,0,Mostnar Karel,E3,40000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40000,0,0,0,0,0
1,73580,2004-07-27 02:18:07,46800.0,1000.0,100.0,3.0,12.41,11.75,0.16,0.16,0.08,0.85,0.04,0.29,0.01,0.02,11.5,11.65,12.00,0,0,0.30,0.7,0.73,0.8,0.9,0.95,1.0,0,0,0.2,20,0,100,500,0,16.5,0.0,0,0,0,0,0,0,0,0,1200,0,0,0,100,625,0,0,0,55,0,0,0,135,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0.0,0,0.0,0,0,0,0,0,Gorensek Peter,E3,40200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40200,0,0,0,0,0
2,73581,2004-07-27 04:46:58,45320.0,800.0,2000.0,3.0,11.24,11.63,0.17,0.18,0.07,0.72,0.04,0.91,0.01,0.02,11.5,11.65,12.00,0,0,0.30,0.7,0.73,0.8,0.9,0.95,1.0,0,0,0.2,15,0,70,400,0,16.5,0.0,0,0,0,0,0,0,0,0,2000,0,0,0,0,490,0,0,0,80,0,0,0,520,0,50,0,0,0,0,0,0,0.0,0,0,0,0,0,0.0,0,0.0,0,0,0,0,0,Gorensek Peter,E3,40200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40200,0,0,0,0,0

всего строк= 3225
всего столбцов= 221

### Удаление данных с нулевой диссперсией

In [3]:
import pandas as pd
pd.set_option('display.max_rows', 10000)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

import plotly.graph_objects as go
from plotly.subplots import make_subplots
data=pd.read_csv('итоговая таблица.csv',sep=';')
#LFVD_CaS LFVD_CoMet  LFVD_Cu LFVD_FeB	LFVD_FeBŽica	LFVD_FeCrNit  LFVD_FeMnA  LFVD_FeNbTa	LFVD_FeNbTafi13 LFVD_FeSiZrŽica	LFVD_FeTi	LFVD_FeTifi13
#LFVD_NiKatode	LFVD_NiOksid	LFVD_OdpCu  LFVD_SiMet  LFVD_KarboritZaVpih	LFVD_Ni90 

display(data.describe())
del_=[]
for i in data.describe().columns:
    if data.describe().loc['std',i]==0:
        del_.append(i)

del_.remove('Ni_LowerLimit')
del_.remove('Ni_Target')
del_.remove('W_LowerLimit')
del_.remove('W_Target')

data.drop(del_,axis=1,inplace=True)
data.drop(['Fill#1_ScrapName','Fill#1_ScrapWeight','Fill#2_ScrapName','Fill#2_ScrapWeight','Fill#3_ScrapName','Fill#3_ScrapWeight','Fill#4_ScrapName',
          'Fill#4_ScrapWeight','Fill#5_ScrapName','Fill#5_ScrapWeight','Fill#6_ScrapName','Fill#6_ScrapWeight'],axis=1,inplace=True)

print('всего строк=',len(data))
print('всего столбцов=',len(data.columns))
data.to_csv('итоговая таблица_испр.csv',sep=';',index=False)

,HeatNo,TotalIngotsWeight,PouringScrap,OtherScrap,Last_EOP,Cr_Last_EOP,Cr_Final,Ni_Last_EOP,Ni_Final,Mo_Last_EOP,Mo_Final,V_Last_EOP,V_Final,W_Last_EOP,W_Final,Cr_LowerLimit,Cr_Target,Cr_UpperLimit,Ni_LowerLimit,Ni_Target,Ni_UpperLimit,Mo_LowerLimit,Mo_Target,Mo_UpperLimit,V_LowerLimit,V_Target,V_UpperLimit,W_LowerLimit,W_Target,W_UpperLimit,LFVD_AlBloki,LFVD_AlGran,LFVD_Boksit,LFVD_CaO,LFVD_CaSi,LFVD_CASIfi13,LFVD_Cfi13,LFVD_CoMet,LFVD_Cu,LFVD_EPŽŽlindra,LFVD_FeAl,LFVD_FeB,LFVD_FeBŽica,LFVD_FeCrNit,LFVD_FeCrA,LFVD_FeCrC,LFVD_FeCrCSi,LFVD_FeCrC51,LFVD_FeMnA,LFVD_FeMnC,LFVD_FeMo,LFVD_FeNbTa,LFVD_FeNbTafi13,LFVD_FeS,LFVD_FeSi,LFVD_FeSiZrŽica,LFVD_FeTi,LFVD_FeTifi13,LFVD_FeV,LFVD_FeW72,LFVD_KarboritMleti,LFVD_MnMet,LFVD_NiGran,LFVD_NiKatode,LFVD_NiOksid,LFVD_OdpCu,LFVD_Polymox,LFVD_SŽica,LFVD_SiMet,LFVD_SiMn,LFVD_SLAGMAG65B,LFVD_KarboritZaVpih,LFVD_Ni90,LFVD_AlŽica,LFVD_Molyquick,LFVD_AlOplašèenaŽica,LFVD_BelaŽlindra,LFVD_Kisik,LFVD_KalcijevKarbid,LFVD_WPaketi,LFVD_SintŽlindra,Fill#1_ScrapWeight,Fill#2_ScrapWeight,Fill#3_ScrapWeight,Fill#4_ScrapWeight,Fill#5_ScrapWeight,Fill#6_ScrapWeight,PV_MKK,PV_PO102,PV_OCR12SPW,PV_OCR8W,PV_PO180,PV_PT181,PV_PT202,PV_PT212,PV_OH239,PV_OSIKRO3,PV_OW4,PV_OCR8VMS,PV_CRV3,PV_OH250,PV_OH252,PV_OH255,PV_OH257,PV_OH258,PV_OH260,PV_OH236NI,PV_UTOPMONI,PV_PKTB,PV_PK3NI,PV_PK332,PV_PK335,PV_PK338,PV_PK340,PV_PK11S,PV_PK343,PV_18MNCR4,PV_PK346,PV_INVAR36,PV_EMCR,PV_SIVA_LITINA,PV_CK10,PV_OC100EX,PV_EC80,PV_VCMO140,PV_VCMO230,PV_31CRV3,PV_ECN150,PV_ECN35,PV_VCNMO200,PV_UTOPNICU,PV_OH807,PV_OCR4PR,PV_OCR12,PV_OCR12SP,PV_OCR12EX,PV_CRV,PV_TMCN2,PV_TMCN1,PV_OSIKRO4,PV_OW1,PV_OCR12VM,PV_CRV2,PV_OSV1,PV_OW6,PV_145V33,PV_UTOP3,PV_UTOPMO2,PV_UTOPEX1,PV_UTOP1,PV_UTOP2,PV_UTOPCO,PV_UTOPEX3,PV_UTOPMO4,PV_UTOPCO2,PV_OV862,PV_UTOPMO6,PV_UTOP33,PV_UTOPSP,PV_UTOPCO3,PV_BRW,PV_BRW1,PV_BRC,PV_BRM2,PV_BRM1,PV_BRM,PV_BRCV,PV_BRC3,PV_BRU,PV_BRCMO,PV_BRCMO2,PV_UTOPTI,PV_12MN,PV_PK2,PV_RAVNIN2,PV_RAVNIN3,PV_RAVNIN4,PV_PK2SP,PV_PK11,PV_PK12,PV_PK13,PV_PKAS,PV_PK15,PV_PK19,PV_PK20,PV_PT929,PV_PK5,PV_PK5M,PV_28304N,PV_PK939,PV_X45,PV_PK942,PV_RAVNAL2,PV_PK10,PV_19MNCR18,PV_214N,PV_OCR8W_OSTRUŽKI,PV_CRV3_OSTRUŽKI,PV_PK335_OSTRUŽKI,PV_CRMO_OSTRUŽKI,PV_CRMO_DROBIŽ,PV_VCNMO200_DROBIŽ,PV_TMCN2_OSTRUŽKI,PV_OCR12VM_OSTRUŽKI,PV_POSEBNA_JEKLA_OSTRUŽKI,PV_BRM2_OSTRUŽKI,PV_E1,PV_E3,PV_E6,PV_E8,PV_Kore,PV_GRODELJ,PV_E40
count,3225.000000,3225.000000,3219.000000,3213.000000,3225.000000,3225.000000,3225.000000,3225.000000,3225.000000,3225.000000,3225.000000,3225.000000,3225.000000,3225.000000,3225.000000,3225.000000,3225.000000,3225.000000,3225.0,3225.0,3225.00000,3225.000000,3225.000000,3225.000000,3225.000000,3225.000000,3225.000000,3225.0,3225.0,3225.000000,3225.000000,3225.000000,3225.000000,3225.000000,3225.0,3225.000000,3225.000000,3225.0,3225.0,3225.000000,3225.000000,3225.0,3225.0,3225.0,3225.000000,3225.000000,3225.000000,3225.000000,3225.0,3225.000000,3225.000000,3225.0,3225.0,3225.000000,3225.000000,3225.0,3225.0,3225.0,3225.000000,3225.000000,3225.000000,3225.000000,3225.000000,3225.0,3225.0,3225.0,3225.000000,3225.000000,3225.0,3225.000000,3225.000000,3225.0,3225.0,3225.000000,3225.0,3225.000000,3225.000000,3225.0,3225.000000,3225.0,3225.000000,3225.000000,2958.000000,2827.000000,980.000000,39.000000,1.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.000000,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.000000,3225.000000,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.000000,3225.0,3225.0,3225.0,3225.0,3225.0,3225.000000,3225.000000,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.000000,3225.000000,3225.0,3225.000000,3225.0,3225.0,3225.0,3225.0,3225.000000,3225.0,3225.0,3225.0,3225.0,3225.0,3225.000000,3225.0,3225.0,3225.0,3225.0,3225.0,3225.000000,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.000000,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.000000,3225.000000,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.0,3225.000000,3225.0,3225.0,3225.0,3225.000000,3225.0,3225.0,3225.0,3225.000000,3225.000000,3225.000000,3225.0,3225.0,3225.0
mean,86307.843411,47257.179845,735.740913,1207.625272,2.136124,10.428981,11.466763,0.176445,0.179643,0.607615,0.756874,0.256205,0.824409,0.042736,0.053622,11.212093,11.476124,11.827783,0.0,0.0,0.28138,0.712496,0.743423,0.849085,0.785104,0.826158,0.902691,0.0,0.0,0.180310,8.486202,1.163721,161.822946,507.568682,0.0,19.714977,13.104403,0.0,0.0,54.538295,0.001550,0.0,0.0,0.0,33.777984,718.937364,27.339535,13.141085,0.0,40.433798,125.738295,0.0,0.0,0.015504,111.045271,0.0,0.0,0.0,342.160930,0.049302,116.794109,0.055814,0.027287,0.0,0.0,0.0,2.612403,0.002574,0.0,9.856434,3.463566,0.0,0.0,0.067380,0.0,2.390233,1.511628,0.0,22.578295,0.0,0.418605,24722.257364,12872.836376,7218.797312,5764.591837,3258.974359,0.0,0.0,0.0,0.0,0.0,0.0,15.503876,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96.744186,22.325581,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.516279,0.0,0.0,0.0,0.0,0.0,34.108527,9.085271,0.0,0.0,0.0,0.0,0.0,0.0,462.945736,3.100775,0.0,1486.263566,0.0,0.0,0.0,0.0,16439.131783,0.0,0.0,0.0,0.0,0.0,1486.666667,0.0,0.0,0.0,0.0,0.0,341.085271,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45.519380,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,229.767442,702.170543,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.418605,0.0,0.0,0.0,6081.829457,0.0,0.0,0.0,2567.054264,14346.133333,249.023256,0.0,0.0,0.0
std,7409.278096,2421.112622,193.340421,961.261362,0.369109,1.725785,0.203419,0.059747,0.046475,0.149729,0.043073,0.106982,0.098484,0.038323,0.039880,0.205359,0.172208,0.194249,0.0,0.0,0.02424,0.038309,0.041661,0.042887,0.095792,0.097292,0.085407,0.0,0.0,0.025337,11.882119,4.527609,78.813026,161.352235,0.0,14.638149,13.661360,0.0,0.0,67.309499,0.088045,0.0,0.0,0.0,110.856382,516.204735,170.567376,122.419621,0.0,34.975266,84.010174,0.0,0.0,0.880451,48.967324,0.0,0.0,0.0,103.484909,1.718672,88.510898,1.846292,1.312235,0.0,0.0,0.0,16.947275,0.111203,0.0,25.318398,21.041522,0.0,0.0,0.633834,0.0,5.889180,7.250948,0.0,26.072744,0.0,7.715773,7689.262444,3743.974869,2220.967884,2032.343514,2411.891368,NaN,0.0,0.0,0.0,0.0,0.0,528.124874,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,836.848301,456.682040,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,398.249101,0.0,0.0,0.0,0.0,0.0,583.118611,394.669744,0.0,0.0,0.0,0.0,0.0,0.0,2251.951319,176.090181,0.0,6152.502100,0.0,0.0,0.0,0.0,10447.862426,0.0,0.0,0.0,0.0,0.0,4186.725250,0.0,0.0,0.0,0.0,0.0,1963.122023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,895.026539,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1781.726092,2376.423748,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,262.751436,0.0,0.0,0.0,2770.801946,0.0,0.0,0.0,10018.943574,8764.408118,1377.659781,0.0,0.0,0.0
min,73579.000000,19450.000000,0.000000,0.000000,1.000000,0.000000,10.900000,0.000000,0.060000,0.000000,0.700000,0.000000,0.290000,0.000000,0.000000,11.000000,11.200000,11.500000,0.0,0.0,0.25000,0.700000,0.720000,0.800000,0.280000,0.300000,0.330000,0.0,0.0,0.100000,0.000000,0.000000,0.000000,0.000000,0.0,-77.500000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,-3.900000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
25%,79685.000000,45840.000000,600.000000,500.000000,2.000000,10.180000,11.330000,0.140000,0.150000,0.550000,0.730000,0.205000,0.750000,0.020000,0.020000,11.100000,11.360000,11.750000,0.0,0.0,0.25000,0.700000,0.730000,0.850000,0.720000,0.760000,0.850000,0.0,0.0,0.150000,3.000000,0.000000,100.000000,400.000000,0.0,14.600000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,320.000000,0.000000,0.000000,0.0,0.000000,70.000000,0.0,0.0,0.000000,80.000000,0.0,0.0,0.0,275.000000,0.000000,50.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,20000.000000,10000.000000,5000.000000,5000.000000,2000.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,10000.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,5000.000000,0.0,0.0,0.0,0.000000,8600.000000,0.000000,0.0,0.0,0.0
50%,86699.000000,47380.000000,800.000000,1000.000000,2.000000,10.630000,11.410000,0.170000,0.170000,0.630000,0.750000,0.270000,0.770000,0.030000,0.040000,11.100000,11.460000,11.750000,0.0,0.0,0.30000,0.700000,0.730000,0.850000,0.720000,0.760000,0.850000,0.0,0.0,0.200000,7.000000,0.000000,150.000000,500.000000,0.0,15.200000,11.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,690.000000,0.000000,0.000000,0.0,39.000000,110.000000,0.0,0.0,0.000000,115.000000,0.0,0.0,0.0,325.000000,0.000000,100.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,1.900000,0.000000,0.0,0.000000,0.0,0.000000,22500.000000,13200.000000,8000.000000,5000.000000,3000.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,17000.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,7000.000000,0.0,0.0,0.0,0.000000,14600.000000,0.000000,0.0,0.0,0.0
75%,92985.000000,48600.000000,800.000000,1600.000000,2.000000,11.070000,11.580000,0.210000,0.210000,0.690000,0.760000,0.322000,0.930000,0.060000,0.070000,11.250000,11.600000,11.750000,0.0,0.0,0.30000,0.700000,0.730000,0.850000,0.900000,0.940000,1.000000,0.0,0.0,0.200000,12.000000,0.000000,210.000000,600.000000,0.0,16.500000,21.800000,0.0,0.0,120.000000,0.000000,0.0,0.0,0.0,0.000000,1040.000000,0.000000,0.000000,0.0,61.000000,170.000000,0.0,0.0,0.000000,140.000000,0.0,0.0,0.0,405.000000,0.000000,165.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,3.900000,0.000000,0.0,50.000000,0.0,0.000000,30000.000000,15000.000000,8000.000000,8000.000000,4900.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,24000.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,8000.000000,0.0,0.0,0.0,0.000000,19500.000000,0.000000,0.0,0.0,0.0
max,98255.000000,57480.000000,1900.000000,25000.000000,3.000000,15.010000,12.500000,0.830000,0.580000,1.100000,1.100000,0.710000,1.090000,0.490000,0.480000,12.000000,12.330000,13.000000,0.0,0.0,0.35000,0.900000,1.000000,1.200000,0.900000,1.000000,1.100000,0.0,0.0,0.500000,552.000000,40.000000,700.000000,1350.000000,0.0,276.300000,128.800000,0.0,0.0,350.000000,5.000000,0.0,0.0,0.0,1300.000000,3700.000000,2470.000000,2100.000000,0.0,275.000000,720.000000,0.0,0.0,50.000000,845.000000,0.0,0.0,0.0,680.000000,90.000000,725.000000,70.000000,73.000000,0.0,0.0,0.0,260.000000,5.800000,0.0,330.000000,250.000000,0.0,0.0,14.500000,0.0,302.000000,50.000000,0.0,200.000000,0.0,200.000000,50000.000000,22500.000000,15000.000000,10000.000000,8100.000000,0.0,0.0,0.0,0.0,0.0,0.0,20000.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20000.000000,10000.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10760.000000,0.0,0.0,0.0,0.0,0.0,10000.000000,20700.000000,0.0,0.0,0.0,0.0,0.0,0.0,20000.000000,10000.000000,0.0,36000.000000,0.0,0.0,0.0,0.0,50000.000000,0.0,0.0,0.0,0.0,0.0,30000.000000,0.0,0.0,0.0,0.0,0.0,20000.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,35000.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30000.000000,20000.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5500.000000,0.0,0.0,0.0,22000.000000,0.0,0.0,0.0,49300.000000,46100.000000,34600.000000,0.0,0.0,0.0

KeyboardInterrupt:

### Проверка взаимных корреляций

In [7]:
import pandas as pd
pd.set_option('display.max_rows', 10000)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

import plotly.graph_objects as go
from plotly.subplots import make_subplots
data=pd.read_csv('итоговая таблица_испр.csv',sep=';')
data_=data.drop(['HeatNo','Date'],axis=1)

corr=data_.corr()

print('число столбцов в таблице=',len(data_.corr()))

display(corr.head(3))
gran_corr_value=0.8
corr_={i:[] for i in corr.columns}
for i in range(len(corr.columns)):    
    mas=corr[corr.columns[i]].tolist()
    el=mas[i]
    ind_max=[j for j in range(len(mas)) if (mas[j]>gran_corr_value)&(j!=i)]
    mas.remove(mas[i])
    corr_[corr.columns[i]]=[min(mas),max(mas)]+[corr.columns[j] for j in ind_max]
    print(corr.columns[i],':',corr_[corr.columns[i]])

число столбцов в таблице= 79

,TotalIngotsWeight,PouringScrap,OtherScrap,Last_EOP,Cr_Last_EOP,Cr_Final,Ni_Last_EOP,Ni_Final,Mo_Last_EOP,Mo_Final,V_Last_EOP,V_Final,W_Last_EOP,W_Final,Cr_LowerLimit,Cr_Target,Cr_UpperLimit,Ni_LowerLimit,Ni_Target,Ni_UpperLimit,Mo_LowerLimit,Mo_Target,Mo_UpperLimit,V_LowerLimit,V_Target,V_UpperLimit,W_LowerLimit,W_Target,W_UpperLimit,LFVD_AlBloki,LFVD_AlGran,LFVD_Boksit,LFVD_CaO,LFVD_CASIfi13,LFVD_Cfi13,LFVD_EPŽŽlindra,LFVD_FeAl,LFVD_FeCrA,LFVD_FeCrC,LFVD_FeCrCSi,LFVD_FeCrC51,LFVD_FeMnC,LFVD_FeMo,LFVD_FeS,LFVD_FeSi,LFVD_FeV,LFVD_FeW72,LFVD_KarboritMleti,LFVD_MnMet,LFVD_NiGran,LFVD_Polymox,LFVD_SŽica,LFVD_SiMn,LFVD_SLAGMAG65B,LFVD_AlŽica,LFVD_AlOplašèenaŽica,LFVD_BelaŽlindra,LFVD_KalcijevKarbid,LFVD_SintŽlindra,PV_PT181,PV_OH252,PV_OH255,PV_EMCR,PV_VCMO230,PV_31CRV3,PV_OCR12,PV_OCR12SP,PV_CRV,PV_OCR12VM,PV_UTOPMO2,PV_UTOPMO4,PV_PK2,PV_PK5,PV_PK5M,PV_CRMO_OSTRUŽKI,PV_OCR12VM_OSTRUŽKI,PV_E3,PV_E6,PV_E8
TotalIngotsWeight,1.000000,0.193895,-0.254886,-0.018212,-0.030634,-0.006719,-0.001496,0.017638,-0.019188,-0.019662,-0.030408,-0.085185,0.010512,0.008139,0.011415,-0.009487,0.044226,NaN,NaN,0.052162,-0.007620,-0.014656,-0.010016,-0.082824,-0.083237,-0.072390,NaN,NaN,0.015322,0.117310,0.075504,-0.002983,0.019300,0.026139,0.104301,-0.001430,0.023374,-0.016840,0.154830,0.037690,0.001116,0.011485,0.094345,0.000748,0.007549,0.091858,-0.029697,0.018623,0.007585,0.001303,0.000867,0.034084,-0.012471,0.018171,0.010136,0.113065,-0.011756,-0.055413,-0.037188,0.024510,-0.020089,-0.007655,0.004603,0.002133,0.004109,-0.020885,0.000748,0.050590,0.021040,-0.029266,-0.010435,-0.019608,0.026790,0.033805,0.008428,0.074344,-0.049151,0.096614,-0.024993
PouringScrap,0.193895,1.000000,-0.078162,0.017521,0.031799,0.088103,0.002218,-0.003991,0.021256,0.059037,-0.054236,0.006268,-0.012892,0.000405,0.114075,0.083393,0.092884,NaN,NaN,-0.018930,0.084875,0.075294,-0.004290,0.014989,0.016541,0.004596,NaN,NaN,-0.048025,0.023879,-0.026827,-0.037235,0.008958,0.038870,0.028632,0.026349,0.024098,0.002625,0.034857,0.032957,-0.054380,0.025322,0.020552,-0.030617,-0.005295,0.074667,-0.013064,-0.001249,-0.032557,0.001658,0.021640,0.031672,0.005427,0.017456,-0.026377,0.018040,0.018342,0.048341,0.039906,0.021931,-0.000674,0.003962,-0.031936,0.033234,0.017507,-0.000646,-0.012378,0.058317,-0.073148,0.036168,0.009558,0.008510,-0.011251,-0.017526,0.012150,-0.021198,-0.000013,0.045710,-0.031286
OtherScrap,-0.254886,-0.078162,1.000000,-0.036516,-0.024331,-0.019767,0.036869,0.045214,0.021680,0.019361,0.003034,0.037111,0.027097,0.029374,0.005674,0.006331,0.001780,NaN,NaN,-0.022400,0.010236,0.016763,0.010006,0.033171,0.032709,0.032081,NaN,NaN,-0.009469,0.000931,-0.011348,-0.019453,0.004866,0.007424,0.030614,-0.025415,-0.020334,0.057823,0.108631,0.041998,-0.021454,-0.039779,-0.001810,-0.005648,0.040637,0.058053,0.042075,-0.015631,-0.011972,0.020997,-0.008418,-0.011522,0.014011,0.022476,-0.029652,-0.017027,0.026149,-0.048462,-0.006088,-0.004518,-0.014324,0.013203,0.017464,0.017276,0.026192,0.013546,0.032905,-0.002094,0.014537,0.004309,-0.002781,0.039013,-0.018009,-0.008263,-0.000744,0.002466,-0.033679,0.002294,0.002639

TotalIngotsWeight : [-0.2548857880374442, 0.1938947163389938]
PouringScrap : [-0.0781619651549336, 0.1938947163389938]
OtherScrap : [-0.2548857880374442, 0.10863098303584492]
Last_EOP : [-0.1272030926285961, 0.19882258802755454]
Cr_Last_EOP : [-0.22158959705738995, 0.5703257239741935]
Cr_Final : [-0.28440093332722877, 0.8570269303797001, 'Cr_LowerLimit', 'Cr_Target', 'Cr_UpperLimit']
Ni_Last_EOP : [-0.4225057407910144, 0.8493834621742896, 'Ni_Final']
Ni_Final : [-0.46317168012383153, 0.8493834621742896, 'Ni_Last_EOP']
Mo_Last_EOP : [-0.6553571814293464, 0.5703257239741935]
Mo_Final : [-0.19993592022803863, 0.8801246792951181, 'Mo_LowerLimit', 'Mo_Target']
V_Last_EOP : [-0.611460745932527, 0.74181442982994]
V_Final : [-0.3442000587005158, 0.9630762688232342, 'V_LowerLimit', 'V_Target', 'V_UpperLimit']
W_Last_EOP : [-0.18926726709134445, 0.8781985163381327, 'W_Final']
W_Final : [-0.244838298267224, 0.8781985163381327, 'W_Last_EOP']
Cr_LowerLimit : [-0.3677663476251769, 0.9307891515298516, 'Cr_Final', 'Cr_Target', 'Cr_UpperLimit']
Cr_Target : [-0.2797287767715427, 0.9307891515298516, 'Cr_Final', 'Cr_LowerLimit', 'Cr_UpperLimit']
Cr_UpperLimit : [-0.21884286743224768, 0.8782259779129036, 'Cr_Final', 'Cr_LowerLimit', 'Cr_Target']
Ni_LowerLimit : [nan, nan]
Ni_Target : [nan, nan]
Ni_UpperLimit : [-0.15035668786812278, 0.7651792969865289]
Mo_LowerLimit : [-0.23775130701585162, 0.9728025210988815, 'Mo_Final', 'Mo_Target']
Mo_Target : [-0.2146888430841305, 0.9728025210988815, 'Mo_Final', 'Mo_LowerLimit']
Mo_UpperLimit : [-0.36752129834479424, 0.7456271021197949]
V_LowerLimit : [-0.36542207483046396, 0.9988026100530947, 'V_Final', 'V_Target', 'V_UpperLimit']
V_Target : [-0.36680269959595835, 0.9988026100530947, 'V_Final', 'V_LowerLimit', 'V_UpperLimit']
V_UpperLimit : [-0.36752129834479424, 0.9861840266381929, 'V_Final', 'V_LowerLimit', 'V_Target']
W_LowerLimit : [nan, nan]
W_Target : [nan, nan]
W_UpperLimit : [-0.23775130701585162, 0.7651792969865289]
LFVD_AlBloki : [-0.11363988152305932, 0.21205572393996783]
LFVD_AlGran : [-0.20517497512256275, 0.1436634997711323]
LFVD_Boksit : [-0.18884759349651445, 0.4335123337718992]
LFVD_CaO : [-0.13539582328785665, 0.4335123337718992]
LFVD_CASIfi13 : [-0.07656686957611698, 0.3152432573292053]
LFVD_Cfi13 : [-0.10090641720523275, 0.111655839658843]
LFVD_EPŽŽlindra : [-0.17692531733604686, 0.30556967323836504]
LFVD_FeAl : [-0.027715406835161133, 0.0816342085543149]
LFVD_FeCrA : [-0.18026250913243078, 0.29389082884321044]
LFVD_FeCrC : [-0.22158959705738995, 0.20855623582938945]
LFVD_FeCrCSi : [-0.21176950277877285, 0.45217095168279364]
LFVD_FeCrC51 : [-0.08678708954410914, 0.10856045068155283]
LFVD_FeMnC : [-0.3244440111928084, 0.22619356354884976]
LFVD_FeMo : [-0.6553571814293464, 0.20867505805547443]
LFVD_FeS : [-0.03061653629733324, 0.031856284475149016]
LFVD_FeSi : [-0.11624301371302916, 0.3994110021886493]
LFVD_FeV : [-0.611460745932527, 0.6741191397350179]
LFVD_FeW72 : [-0.02969662518801547, 0.045867932981534174]
LFVD_KarboritMleti : [-0.15232574142483932, 0.3994110021886493]
LFVD_MnMet : [-0.03495912635776982, 0.1195998755535158]
LFVD_NiGran : [-0.03272860933626207, 0.08428194981721232]
LFVD_Polymox : [-0.12540444781559415, 0.09106946118895135]
LFVD_SŽica : [-0.04138939642997011, 0.0656024917121267]
LFVD_SiMn : [-0.3244440111928084, 0.29389082884321044]
LFVD_SLAGMAG65B : [-0.10146508916798287, 0.21205572393996783]
LFVD_AlŽica : [-0.0920859617631805, 0.04745587856130995]
LFVD_AlOplašèenaŽica : [-0.059285963712148226, 0.11306484306125347]
LFVD_BelaŽlindra : [-0.1805881275879598, 0.45217095168279364]
LFVD_KalcijevKarbid : [-0.20517497512256275, 0.30556967323836504]
LFVD_SintŽlindra : [-0.05781678917983711, 0.06600801502700382]
PV_PT181 : [-0.04749940735299065, 0.44543560907286883]
PV_OH252 : [-0.12498115959942221, 0.17632986909494155]
PV_OH255 : [-0.04964087809356343, 0.10162274540655608]
PV_EMCR : [-0.03193624552799527, 0.0991167234632762]
PV_VCMO230 : [-0.05066932751042306, 0.03323414915260621]
PV_31CRV3 : [-0.05054375547834532, 0.6321106182110643]
PV_OCR12 : [-0.0902862949057401, 0.12092511776323482]
PV_OCR12SP : [-0.038663269802419985, 0.07459763892995452]
PV_CRV : [-0.3610110587743057, 0.30472022818894506]
PV_OCR12VM : [-0.5991187295602307, 0.74181442982994]
PV_UTOPMO2 : [-0.2047960434097931, 0.18222653729998173]
PV_UTOPMO4 : [-0.07838179458297129, 0.10143662370549247]
PV_PK2 : [-0.07877254741292161, 0.6321106182110643]
PV_PK5 : [-0.09791465186288642, 0.10940614604858251]
PV_PK5M : [-0.1346233968285453, 0.13252869108699147]
PV_CRMO_OSTRUŽKI : [-0.12048738389604295, 0.44543560907286883]
PV_OCR12VM_OSTRUŽKI : [-0.5554381325334004, 0.48760943446218497]
PV_E3 : [-0.5554381325334004, 0.43368083272622177]
PV_E6 : [-0.46317168012383153, 0.20867505805547443]
PV_E8 : [-0.29596808561018434, 0.17229197571400548]

### Гистограмма превышения целевого значения по компонентам

#### TODO
- создать гистограммы по отдельным сталеварам
- выявить случаи брака, превышение или занижение по элементу

In [4]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

data['Cr_exceed']=data.apply(lambda x:x['Cr_Final']-x['Cr_Target'],axis=1)
data['Ni_exceed']=data.apply(lambda x:x['Ni_Final']-x['Ni_Target'],axis=1)
data['Mo_exceed']=data.apply(lambda x:x['Mo_Final']-x['Mo_Target'],axis=1)
data['V_exceed']=data.apply(lambda x:x['V_Final']-x['V_Target'],axis=1)
data['W_exceed']=data.apply(lambda x:x['W_Final']-x['W_Target'],axis=1)

print('в среднем разница между Cr_Target и Cr_LowerLimit =',data.apply(lambda x:x['Cr_Target']-x['Cr_LowerLimit'],axis=1).mean())
print('в среднем разница между Ni_Target и Ni_LowerLimit =',data.apply(lambda x:x['Ni_Target']-x['Ni_LowerLimit'],axis=1).mean())
print('в среднем разница между Mo_Target и Mo_LowerLimit =',data.apply(lambda x:x['Mo_Target']-x['Mo_LowerLimit'],axis=1).mean())
print('в среднем разница между V_Target и V_LowerLimit =',data.apply(lambda x:x['V_Target']-x['V_LowerLimit'],axis=1).mean())
print('в среднем разница между W_Target и W_LowerLimit =',data.apply(lambda x:x['W_Target']-x['W_LowerLimit'],axis=1).mean())

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(go.Histogram(x=data['Cr_exceed'],xbins=dict(start=-0.2, end= 0.2, size=0.005), name='Гистограмма превышения Cr'))
fig.add_trace(go.Histogram(x=data['Ni_exceed'],xbins=dict(start=-0.5, end= 0.5, size=0.005), name='Гистограмма превышения Ni'))
fig.add_trace(go.Histogram(x=data['Mo_exceed'],xbins=dict(start=-0.2, end= 0.2, size=0.005), name='Гистограмма превышения Mo'))
fig.add_trace(go.Histogram(x=data['V_exceed'],xbins=dict(start=-0.2, end= 0.2, size=0.005), name='Гистограмма превышения V'))
fig.add_trace(go.Histogram(x=data['W_exceed'],xbins=dict(start=-0.2, end= 0.2, size=0.005), name='Гистограмма превышения W'))
#fig.add_trace(go.Histogram(x=data['Cr_exceed'], name='Гистограмма превышения Cr'))
fig.show()

C:\Users\Amega\AppData\Local\Temp\ipykernel_11168\798717135.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data['Cr_exceed']=data.apply(lambda x:x['Cr_Final']-x['Cr_Target'],axis=1)
C:\Users\Amega\AppData\Local\Temp\ipykernel_11168\798717135.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data['Ni_exceed']=data.apply(lambda x:x['Ni_Final']-x['Ni_Target'],axis=1)
C:\Users\Amega\AppData\Local\Temp\ipykernel_11168\798717135.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data['Mo_exceed']=data.apply(lambda x:x['Mo_Final']-x['Mo_Target'],axis=1)
C:\Users\Amega\AppData\Local\Temp\ipykernel_11168\798717135.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data['V_exceed']=data.apply(lambda x:x['V_Final']-x['V_Target'],axis=1)
C:\Users\Amega\AppData\Local\Temp\ipykernel_11168\798717135.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data['W_exceed']=data.apply(lambda x:x['W_Final']-x['W_Target'],axis=1)

в среднем разница между Cr_Target и Cr_LowerLimit = 0.26403100775193833
в среднем разница между Ni_Target и Ni_LowerLimit = 0.0
в среднем разница между Mo_Target и Mo_LowerLimit = 0.030927131782945757
в среднем разница между V_Target и V_LowerLimit = 0.041054263565891466
в среднем разница между W_Target и W_LowerLimit = 0.0

In [45]:
data['Cr_adviser_target']=data.apply(lambda x:(x['Cr_Target']+x['Cr_LowerLimit'])/2,axis=1)
data['Ni_adviser_target']=data.apply(lambda x:(x['Ni_Target']+x['Ni_LowerLimit'])/2,axis=1)
data['Cr_exceed']=data.apply(lambda x:x['Cr_Final']-x['Cr_adviser_target'],axis=1)
data['Ni_exceed']=data.apply(lambda x:x['Ni_Final']-x['Ni_adviser_target'],axis=1)

print('в среднем разница между Cr_Target и Cr_LowerLimit =',data.apply(lambda x:x['Cr_Target']-x['Cr_LowerLimit'],axis=1).mean())
print('в среднем разница между Ni_Target и Ni_LowerLimit =',data.apply(lambda x:x['Ni_Target']-x['Ni_LowerLimit'],axis=1).mean())

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(go.Histogram(x=data['Cr_exceed'],xbins=dict(start=-0.2, end= 0.2, size=0.005), name='Гистограмма превышения Cr'))
fig.add_trace(go.Histogram(x=data['Ni_exceed'],xbins=dict(start=-0.5, end= 0.5, size=0.005), name='Гистограмма превышения Ni'))
#fig.add_trace(go.Histogram(x=data['Cr_exceed'], name='Гистограмма превышения Cr'))
fig.show()

в среднем разница между Cr_Target и Cr_LowerLimit = 0.26403100775193833
в среднем разница между Ni_Target и Ni_LowerLimit = 0.0

### Экономический эффект

In [46]:
display(data[['TotalIngotsWeight','Cr_Last_EOP','Cr_Final','LFVD_FeCrA','LFVD_FeCrC',]].head(3))
print('количество строк с большим исходным составом=',len(data[(data['LFVD_FeCrA']==0)&(data['LFVD_FeCrC']==0)&(data['LFVD_FeCrCSi']==0)&(data['LFVD_FeCrC51']==0)]))

display(data[['TotalIngotsWeight','Ni_Last_EOP','Ni_Final','LFVD_NiGran']].head(3))
print('количество строк с большим исходным составом=',len(data[(data['LFVD_NiGran']==0)]))

display(data[['TotalIngotsWeight','Mo_Last_EOP','Mo_Final','LFVD_FeMo','LFVD_Polymox']].head(3))
print('количество строк с большим исходным составом=',len(data[(data['LFVD_FeMo']==0)&(data['LFVD_Polymox']==0)]))

display(data[['TotalIngotsWeight','V_Last_EOP','V_Final','LFVD_FeV']].head(3))
print('количество строк с большим исходным составом=',len(data[(data['LFVD_FeV']==0)]))

display(data[['TotalIngotsWeight','W_Last_EOP','W_Final','LFVD_FeW72']].head(3))
print('количество строк с большим исходным составом=',len(data[(data['LFVD_FeW72']==0)]))

   TotalIngotsWeight  Cr_Last_EOP  Cr_Final  LFVD_FeCrA  LFVD_FeCrC
0            49440.0         9.71     11.30           0        2400
1            46800.0        12.41     11.75           0        1200
2            45320.0        11.24     11.63           0        2000

количество строк с большим исходным составом= 235

   TotalIngotsWeight  Ni_Last_EOP  Ni_Final  LFVD_NiGran
0            49440.0         0.20      0.21            0
1            46800.0         0.16      0.16            0
2            45320.0         0.17      0.18            0

количество строк с большим исходным составом= 3223

   TotalIngotsWeight  Mo_Last_EOP  Mo_Final  LFVD_FeMo  LFVD_Polymox
0            49440.0         0.12      0.71        520             0
1            46800.0         0.08      0.85        625             0
2            45320.0         0.07      0.72        490             0

количество строк с большим исходным составом= 115

   TotalIngotsWeight  V_Last_EOP  V_Final  LFVD_FeV
0            49440.0        0.03     0.90       580
1            46800.0        0.04     0.29       135
2            45320.0        0.04     0.91       520

количество строк с большим исходным составом= 9

   TotalIngotsWeight  W_Last_EOP  W_Final  LFVD_FeW72
0            49440.0        0.01     0.02           0
1            46800.0        0.01     0.02           0
2            45320.0        0.01     0.02           0

количество строк с большим исходным составом= 3219

In [11]:
data_cr=data[(data['Cr_Final']>data['Cr_Last_EOP'])&(data['Cr_Final']>data['Cr_Target'])]
data_cr=data_cr.copy()

data_cr['FeCr_1%']=data_cr.apply(lambda x: (x['LFVD_FeCrA']+x['LFVD_FeCrC'])/(x['Cr_Final']-x['Cr_Last_EOP'])/x['TotalIngotsWeight']*100,axis=1)
data_cr['Cr_surplus']=data_cr.apply(lambda x:(x['LFVD_FeCrA']+x['LFVD_FeCrC'])-(x['Cr_Target']-x['Cr_Last_EOP'])*x['TotalIngotsWeight']*x['FeCr_1%']/100,axis=1)
display(data_cr[['TotalIngotsWeight','Cr_Last_EOP','Cr_Target','Cr_Final','LFVD_FeCrA','LFVD_FeCrC','FeCr_1%','Cr_surplus']].head(3))
print('перерасход в год FeCr=',round(data_cr['Cr_surplus'].sum()/10,0),'кг',' примерная стоимость=',round(data_cr['Cr_surplus'].sum()/10*300/1000000,2),'млн.руб')

   TotalIngotsWeight  Cr_Last_EOP  Cr_Target  Cr_Final  LFVD_FeCrA  LFVD_FeCrC   FeCr_1%  Cr_surplus
0            49440.0         9.71      11.26     11.30           0        2400  3.053062   60.377358
7            51460.0        10.54      11.26     11.45           0        1300  2.776081  271.428571
9            46800.0         9.95      11.76     11.79           0         600  0.696767    9.782609

перерасход в год FeCr= 8264.0 кг  примерная стоимость= 2.48 млн.руб

In [12]:
data_mo=data[(data['Mo_Final']>data['Mo_Last_EOP'])&(data['Mo_Final']>data['Mo_Target'])]
data_mo=data_mo.copy()

data_mo['FeMo_1%']=data_mo.apply(lambda x: (x['LFVD_FeMo']+x['LFVD_Polymox'])/(x['Mo_Final']-x['Mo_Last_EOP'])/x['TotalIngotsWeight']*100,axis=1)
data_mo['Mo_surplus']=data_mo.apply(lambda x:(x['LFVD_FeMo']+x['LFVD_Polymox'])-(x['Mo_Target']-x['Mo_Last_EOP'])*x['TotalIngotsWeight']*x['FeMo_1%']/100,axis=1)
display(data_mo[['TotalIngotsWeight','Mo_Last_EOP','Mo_Target','Mo_Final','LFVD_FeMo','FeMo_1%','Mo_surplus']].head(3))
print('перерасход в год Mo=',round(data_mo['Mo_surplus'].sum()/10,0),'кг',' примерная стоимость=',round(data_mo['Mo_surplus'].sum()/10*1500/1000000,2),'млн.руб')

   TotalIngotsWeight  Mo_Last_EOP  Mo_Target  Mo_Final  LFVD_FeMo   FeMo_1%  Mo_surplus
1            46800.0         0.08       0.73      0.85        625  1.734377   97.402597
5            43800.0         0.46       0.73      0.75        235  1.850102   16.206897
6            48100.0         0.50       0.73      0.74        195  1.689189    8.125000

перерасход в год Mo= 4399.0 кг  примерная стоимость= 6.6 млн.руб

In [13]:
data_v=data[(data['V_Final']>data['V_Last_EOP'])&(data['V_Final']>data['V_Target'])]
data_v=data_v.copy()

data_v['FeV_1%']=data_v.apply(lambda x: (x['LFVD_FeV'])/(x['V_Final']-x['V_Last_EOP'])/x['TotalIngotsWeight']*100,axis=1)
data_v['V_surplus']=data_v.apply(lambda x:(x['LFVD_FeV'])-(x['V_Target']-x['V_Last_EOP'])*x['TotalIngotsWeight']*x['FeV_1%']/100,axis=1)
display(data_v[['TotalIngotsWeight','V_Last_EOP','V_Target','V_Final','LFVD_FeV','FeV_1%','V_surplus']].head(3))
print('перерасход в год V=',round(data_v['V_surplus'].sum()/10,0),'кг',' примерная стоимость=',round(data_v['V_surplus'].sum()/10*1500/1000000,2),'млн.руб')

   TotalIngotsWeight  V_Last_EOP  V_Target  V_Final  LFVD_FeV    FeV_1%  V_surplus
6            48100.0        0.38      0.76     0.77       240  1.279386   6.153846
8            48960.0        0.31      0.66     0.69       235  1.263115  18.552632
9            46800.0        0.05      0.30     0.33       160  1.221001  17.142857

перерасход в год V= 1229.0 кг  примерная стоимость= 1.84 млн.руб

In [24]:
data_w=data[(data['W_Final']>data['W_Last_EOP'])&(data['W_Final']>data['W_Target'])]
data_w=data_w.copy()

data_w['FeW_1%']=data_w.apply(lambda x: (x['LFVD_FeW72'])/(x['W_Final']-x['W_Last_EOP'])/x['TotalIngotsWeight']*100,axis=1)
data_w['W_surplus']=data_w.apply(lambda x:(x['LFVD_FeW72'])-(x['W_Target']-x['W_Last_EOP'])*x['TotalIngotsWeight']*x['FeW_1%']/100,axis=1)
display(data_w[['TotalIngotsWeight','W_Last_EOP','W_Target','W_Final','LFVD_FeW72','FeW_1%','W_surplus']].head(3))
print('перерасход в год W=',round(data_w['W_surplus'].sum()/10,0),'кг',' примерная стоимость=',round(data_w['W_surplus'].sum()/10*1500/1000000,2),'млн.руб')

   TotalIngotsWeight  W_Last_EOP  W_Target  W_Final  LFVD_FeW72  FeW_1%  W_surplus
0            49440.0        0.01         0     0.02           0     0.0        0.0
1            46800.0        0.01         0     0.02           0     0.0        0.0
2            45320.0        0.01         0     0.02           0     0.0        0.0

перерасход в год W= 19.0 кг  примерная стоимость= 0.03 млн.руб

### Данные по отдельным сталеварам

In [ ]:
#'Cr_surplus', 'Mo_surplus', 'V_surplus', 'W_surplus', 'Total_defects' 
data_unique_emp = pd.DataFrame(data['LFVD_ShiftHead'].unique(), columns=['LFVD_ShiftHead'])

fig = make_subplots(specs=[[{"secondary_y": True}]])

for emp in data_unique_emp['LFVD_ShiftHead']:
    deffects = data.agg(lambda x: 1 if x['LFVD_ShiftHead']==emp and (x['Cr_Final'] > x['Cr_Last_EOP']) and (x['Cr_Final'] > x['Cr_Target']) else 0, axis=1).sum()
    data_unique_emp.loc[data_unique_emp['LFVD_ShiftHead']==emp, 'Cr_defects']=deffects 
    data_unique_emp.loc[data_unique_emp['LFVD_ShiftHead']==emp, 'Total_defects']=deffects
    deffects = data.agg(lambda x: 1 if x['LFVD_ShiftHead']==emp and (x['Ni_Final'] > x['Ni_Last_EOP']) and (x['Ni_Final'] > x['Ni_Target']) else 0, axis=1).sum()
    data_unique_emp.loc[data_unique_emp['LFVD_ShiftHead']==emp, 'Ni_defects']=deffects 
    data_unique_emp.loc[data_unique_emp['LFVD_ShiftHead']==emp, 'Total_defects']+=deffects
    deffects = data.agg(lambda x: 1 if x['LFVD_ShiftHead']==emp and (x['Mo_Final'] > x['Mo_Last_EOP']) and (x['Mo_Final'] > x['Mo_Target']) else 0, axis=1).sum()
    data_unique_emp.loc[data_unique_emp['LFVD_ShiftHead']==emp, 'Mo_defects']=deffects 
    data_unique_emp.loc[data_unique_emp['LFVD_ShiftHead']==emp, 'Total_defects']+=deffects
    deffects = data.agg(lambda x: 1 if x['LFVD_ShiftHead']==emp and (x['V_Final'] > x['V_Last_EOP']) and (x['V_Final'] > x['V_Target']) else 0, axis=1).sum()
    data_unique_emp.loc[data_unique_emp['LFVD_ShiftHead']==emp, 'V_defects']=deffects 
    data_unique_emp.loc[data_unique_emp['LFVD_ShiftHead']==emp, 'Total_defects']+=deffects
    deffects = data.agg(lambda x: 1 if x['LFVD_ShiftHead']==emp and (x['W_Final'] > x['W_Last_EOP']) and (x['W_Final'] > x['W_Target']) else 0, axis=1).sum()
    data_unique_emp.loc[data_unique_emp['LFVD_ShiftHead']==emp, 'W_defects']=deffects
    data_unique_emp.loc[data_unique_emp['LFVD_ShiftHead']==emp, 'Total_defects']+=deffects

for emp in data_unique_emp:
    fig.add_trace(go.Bar(x=[emp], y=[data_unique_emp.loc[data_unique_emp['LFVD_ShiftHead']==emp, 'Total_defects']], name=f'Гистограмма дефектов для {emp}'))
    

fig.show()
display(data_unique_emp)

    LFVD_ShiftHead  Cr_defects  Total_defects  Ni_defects  Mo_defects  V_defects  W_defects
0    Mostnar Karel        29.0          189.0        45.0        41.0       17.0       57.0
1   Gorensek Peter       302.0         2121.0       366.0       539.0      262.0      652.0
2      Baric Mirko        44.0          332.0        59.0        88.0       41.0      100.0
3   Kotnik Marijan       324.0         2106.0       311.0       653.0      288.0      530.0
4        Ferk Jože        71.0          396.0        57.0        98.0       61.0      109.0
5        Adam Maks       341.0         1984.0       293.0       482.0      325.0      543.0
6   Hermonko Miran         5.0           37.0         4.0         7.0        5.0       16.0
7     Lukman Elvis         1.0            9.0         1.0         2.0        2.0        3.0
8    Petrič Damjan         6.0           23.0         2.0         3.0        4.0        8.0
9   Obrovnik Boris        32.0          169.0        34.0        45.0       20.0       38.0
10      Ramot Ivan        14.0           91.0        17.0        20.0       18.0       22.0
11  Kališnik Franc         6.0           31.0         4.0         5.0        3.0       13.0
12       Krof Miha         6.0           18.0         5.0         3.0        3.0        1.0

### Выявление случаев брака

### Какая стоимость перерасхода если нам удастся обеспечить среднее значение между Cr_LowerLimit и Cr_Target?

### Выполните расчеты для каждого элемента: Mo, Ni, V, W

In [ ]:
import pandas as pd
import dtreeviz
from sklearn.tree import DecisionTreeClassifier

random_state=42
data=pd.read_csv('итоговая таблица_испр.csv',sep=';')
data.fillna(0,inplace=True)
#display(data)
data['quality']=data.apply(lambda x: 1 if x['Cr_Final']<=x['Cr_Target'] else 0,axis=1)

X=data.drop(['HeatNo','quality','Date','Cr_Final','Ni_Final','Mo_Final','V_Final','W_Final'],axis=1).values
y=data['quality'].values

features=data.drop(['HeatNo','Date','Cr_Final','Ni_Final','Mo_Final','V_Final','W_Final'],axis=1).columns.tolist()
class_names=list(set(y))
target='quality'
tree_classifier = DecisionTreeClassifier(max_depth=33, random_state=random_state)
tree_classifier.fit(X, y)

viz_model = dtreeviz.model(tree_classifier,
                           X_train=X, y_train=y,
                           feature_names=features,
                           target_name=target)

viz_model.view(scale=0.8)
#viz_model.save('dtreeviz.svg')